todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:i>/', views.deleteTodoView), 
] 

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls',)),
]

todoapp/models.py
from django.db import models
from django.utils import timezone

from django.db import models
from django.urls import reverse

# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField() 

def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)

class ToDoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("list", args=[self.id])

    def __str__(self):
        return self.title

class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "item-update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

todoapp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 
# Create your views here.
def index(request):
    return render(request, 'index.html')



def todoappView(request):
    all_todo_items = TodoListItem.objects.all()
    return render(request, 'todolist.html',  {'all_items':all_todo_items})


def addTodoView(request):
    # x = request.POST.get('todotext')
    new_item = TodoListItem()
    new_item.content = request.POST.get('content')
    new_item.save()
    return HttpResponseRedirect('/todo/') 

def deleteTodoView(request, i):
    y = TodoListItem.objects.get(id= i)
    y.delete()
    return HttpResponseRedirect('/todo/') 

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>

<style>
  a {
  text-decoration: none;
  border: 3px solid rgb(0, 102, 255);
  color: transparent;
  padding: 40px 80px;
  font-size: 28px;
  font-family: sans-serif;
  letter-spacing: 5px;
  transition: all 0.5s;
  position: relative;
  left:700px;
  top:-70px;
}
a:before {
  content: "Get Started";
  display: flex;
  justify-content: center;
  align-items: center;
  color: rgb(0, 255, 13);
  background: rgb(34, 34, 34);
  font-size: 28px;
  top: 0;
  left: 100%;
  font-family: sans-serif;
  letter-spacing: 5px;
  transition: all 1s;
  height: 100%;
  width: 100%;
  position: absolute;
  transform: scale(0) rotatey(0);
  opacity: 0;
}
a:hover:before {
  transform: scale(1) rotatey(360deg);
  left: 0;
  opacity: 1;
}
a:after {
  content: "Get Started";
  display: flex;
  justify-content: center;
  align-items: center;
  color: rgb(0, 251, 255);
  background: rgb(34, 34, 34);
  font-size: 28px;
  top: 0;
  left: 0;
  font-family: sans-serif;
  letter-spacing: 5px;
  transition: all 1s;
  height: 100%;
  width: 100%;
  position: absolute;
  transform: scale(1) rotatey(0);
  opacity: 1;
}
a:hover:after {
  transform: scale(0) rotatey(360deg);
  left: -100%;
  opacity: 0;
}
</style>

<body style="background-color: black;">
  <div style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;font-size: 100px;
  color: aqua;text-align: center;">ToDo App</div>
    
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'todoapp:todo' %}">Get Started</a>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <img src="{% static 'img/todo.png' %}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 650px; height:150px;">

    



<!-- <div class="container">
    <div class="row">
      <img src="{% static 'img\todo.png' %}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 600px; height:200px;">
    </div>
    <div class="card text-center" style="margin-top: 200px;">
        <div class="card-header">
          Hello!
        </div>
        <div class="card-body">
          <h5 class="card-title">Welcome to the app</h5>
          <p class="card-text">Make life easier by creating ToDo List</p>
          <a href="{% url 'todoapp:todo' %}" class="btn btn-primary">Start Now!</a>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
</div> -->



    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

templates/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Montserrat:600&display=swap');
body{
  margin: 0;
  padding: 0;
  display: flex;
  height: 100vh;
  align-items: center;
  justify-content: center;
  background:rgb(0, 0, 0);
}
span{
  position: relative;
  display: inline-flex;
  width: 180px;
  height: 55px;
  margin: 0 15px;
  perspective: 1000px;
}
span a{
  font-size: 19px;
  letter-spacing: 1px;
  transform-style: preserve-3d;
  transform: translateZ(-25px);
  transition: transform .25s;
  font-family: 'Montserrat', sans-serif;
  
}
span a:before,
span a:after{
  position: absolute;
  content: "ADD";
  height: 55px;
  width: 180px;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 5px solid rgb(255, 255, 255);
  box-sizing: border-box;
  border-radius: 5px;
}
span a:before{
  color: #fff;
  background: rgb(255, 0, 89);
  transform: rotateY(0deg) translateZ(25px);
}
span a:after{
  color: rgb(255, 255, 255);
  transform: rotateX(90deg) translateZ(25px);
}
span a:hover{
  transform: translateZ(-25px) rotateX(-90deg);
}
    </style>

<img src="{% static 'img\images.png' %}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 250px; height:150px;">
    
<div class="container"> 
    <div class="row" style="margin-top: 20px;">
        <div class="col">

            <div class="row">
                <form class="form-inline" action="/addTodoItem/" method = "post">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-8">
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="content" class="sr-only"></label>
                                <input type="text" class="form-control" name="content" placeholder="Research">
                              </div>
                        </div>
                        <div class="col-4" style="margin-top: 25px;">
                            <!-- <button type="submit" class="btn btn-primary mb-2">Add Todo</button> -->
                            <button style="background-color: black;position:relative"><span type="submit"><a href="#"></a></span></button>
                        </div>
                    </div>
                    
                  </form>
            </div>
            {% for i in all_items %} 
            <div class="row">
                <div class="col-1"></div>
                <div class="col-6">
                    <div class="card  text-white bg-dark mb-3">
                        <div class="card-body">
                            {{i.content}}
                        </div>
                      </div>
                </div>

                <div class="col-2">
                    <form action="/deleteTodoItem/{{i.id}}/" method = "post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                          </svg></i>
                        </button>
            </form> 
                </div>
                <div class="col-3"></div>
            </div>
            {% endfor %}
        </div>
    </div>
    


</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>